//============================================================================
// Name        : multiplesOf3and5.cpp
// Author      : 
// Version     :
// Copyright   : Your copyright notice
// Description : Hello World in C++, Ansi-style
//============================================================================



//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//


#include <iostream>
using namespace std;

int main() {

  long int sum = 2;

  long int t1 = 1, t2 = 2, next = 0;

  while(next < 4000000)
  {
    next = t1 + t2;
    if (next % 2 == 0 && next < 4000000)
    {
        sum += next;
    }
    t1 = t2;
    t2 = next;
  }
  cout << sum;
  return 0;
}
